// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTfjc39nfeJKGlRbI9lEa9fso658jTTc',
    appId: '1:1038304186905:android:399a9ab874ba9721bd1088',
    messagingSenderId: '1038304186905',
    projectId: 'karna-b35f8',
    storageBucket: 'karna-b35f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_4dzvS4wFcX3szIM5QnxFbvggnvfKzEA',
    appId: '1:1038304186905:ios:923c171849998177bd1088',
    messagingSenderId: '1038304186905',
    projectId: 'karna-b35f8',
    storageBucket: 'karna-b35f8.appspot.com',
    iosClientId: '1038304186905-8t68h4edt2rhdglk21v4pjj9785ovbsu.apps.googleusercontent.com',
    iosBundleId: 'gangaraju.rohan-gmail.com',
  );
}
